apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: debug
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z db-service 3306; do echo waiting for db; sleep 2; done;",
            ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrate
  labels:
    app: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrate
  template:
    metadata:
      labels:
        app: migrate
    spec:
      containers:
        - name: migrate
          image: ${IMAGE}
          env:
            - name: LOG_LEVEL
              value: debug
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
          command: ["migrate", "--yes"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revert
  labels:
    app: revert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revert
  template:
    metadata:
      labels:
        app: revert
    spec:
      containers:
        - name: revert
          image: ${IMAGE}
          env:
            - name: LOG_LEVEL
              value: debug
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
          command: ["migrate", "--revert", "--yes"]
