name: Unit tests
on: [pull_request]

concurrency:
  cancel-in-progress: true
  group: "build-${{ github.event.pull_request.number || github.ref }}"

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Setup Swift"
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "5.10"
    - name: "Checkout repository"
      uses: actions/checkout@v2
    - name: "Run Unit Tests"
      run: cd CulinaryChroniclesBackend && swift test
